# -*- coding: utf-8 -*-
"""Stable Diffusion GenAi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cWTqpmdenepaV2wWtsw_AAf_s96NWZXO
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install --upgrade diffusers transformers -q

from pathlib import Path
import tqdm
import torch
import pandas as pd
import numpy as np
from diffusers import StableDiffusionPipeline
from transformers import pipeline,set_seed
import matplotlib.pyplot as plt
import cv2

class CFG:
  device = "cuda"
  seed=42
  generator = torch.Generator(device).manual_seed(seed)
  image_gen_steps=35
  image_gen_model_id = "stabilityai/stable-diffusion-2-1"
  image_gen_size = (400,400)
  image_gen_guidance_scale = 9
  prompt_gen_model_id = "gpt-omni/mini-omni"
  prompt_dataset_size = 6
  prompt_max_length = 12

image_gen_model = StableDiffusionPipeline.from_pretrained(
    CFG.image_gen_model_id,
    torch_dtype=torch.float16,
    revision="fp16",
    use_auth_token="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",guidance_scale=9
)

image_gen_model = image_gen_model.to(CFG.device)

def generate_images(prompt,model):
  image = model(
      prompt,
      num_inference_steps=CFG.image_gen_steps,
      generator=CFG.generator,
      guidance_scale=CFG.image_gen_guidance_scale,
  ).images[0]

  image = image.resize(CFG.image_gen_size)
  return image

generate_images('forest',image_gen_model)

generate_images('football stadium filled with crowd',image_gen_model)

generate_images('ronaldo with fifa worldcup',image_gen_model)

generate_images('sunil cheetri with fifa world cup',image_gen_model)

generate_images('virat kohli with ipl trophy',image_gen_model)